import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import * as core from '@actions/core';
import * as github from '@actions/github';

export function configAuthentication(registryUrl: string) {
  const npmrc: string = path.resolve(
    process.env['RUNNER_TEMP'] || process.cwd(),
    '.npmrc'
  );
  if (registryUrl && !registryUrl.endsWith('/')) {
    registryUrl += '/';
  }

  if (registryUrl) {
    writeRegistryToFile(registryUrl, npmrc);
  }

  writeNpmRegistriesToFile(npmrc);
}

interface ParsedRegistryEntry {
  scope: string;
  registry: string;
  token: string;
}

function parseNpmRegistriesInput(raw: string): ParsedRegistryEntry[] {
  const entries: ParsedRegistryEntry[] = [];
  for (const rawLine of raw.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;

    let scope = '';
    let rest = line;

    const eqIdx = rest.indexOf('=');
    if (rest.startsWith('@') && eqIdx > 0) {
      scope = rest.slice(0, eqIdx).trim().toLowerCase();
      rest = rest.slice(eqIdx + 1).trim();
    }

    let registry = rest;
    let token = '';
    const tokIdx = rest.indexOf('::');
    if (tokIdx >= 0) {
      registry = rest.slice(0, tokIdx).trim();
      token = rest.slice(tokIdx + 2).trim();
    }

    if (!registry) {
      core.warning(`Skipping invalid npm-registries entry: "${line}"`);
      continue;
    }
    if (!registry.endsWith('/')) registry += '/';

    entries.push({scope, registry, token});
  }
  return entries;
}

function writeNpmRegistriesToFile(fileLocation: string) {
  const raw = core.getInput('npm-registries');
  if (!raw) return;

  const entries = parseNpmRegistriesInput(raw);
  if (entries.length === 0) return;

  core.debug(
    `Writing ${entries.length} npm-registries entrie(s) to ${fileLocation}`
  );

  const outLines: string[] = [];
  for (const {scope, registry, token} of entries) {
    if (scope) {
      outLines.push(`${scope}:registry=${registry}`);
    } else {
      outLines.push(`registry=${registry}`);
    }
    if (token) {
      const host = registry.replace(/^\w+:/, '');
      outLines.push(`${host}:_authToken=${token}`);
    }
  }

  const existing = fs.existsSync(fileLocation)
    ? fs.readFileSync(fileLocation, 'utf8')
    : '';
  const separator = existing.length && !existing.endsWith(os.EOL) ? os.EOL : '';
  fs.writeFileSync(
    fileLocation,
    existing + separator + outLines.join(os.EOL) + os.EOL
  );
  core.exportVariable('NPM_CONFIG_USERCONFIG', fileLocation);

  // Publish target = first scoped entry. Rewrite ./package.json name so
  // `npm publish` routes to that scope's registry regardless of what's on disk.
  const publishEntry = entries.find(e => e.scope);
  if (publishEntry) {
    applyPublishScope(publishEntry.scope, './package.json');
  }

  // Generate helper script $NPM_PUBLISH_ALL that publishes to every scoped
  // entry, rewriting package.json.name between each publish. Any args passed
  // to the script are forwarded to every `npm publish` invocation.
  const scopedEntries = entries.filter(e => e.scope);
  if (scopedEntries.length > 0) {
    writeNpmPublishAllScript(scopedEntries.map(e => e.scope));
  }
}

function writeNpmPublishAllScript(scopes: string[]) {
  const pkgPath = path.resolve(process.cwd(), './package.json');
  if (!fs.existsSync(pkgPath)) {
    core.debug('No package.json in cwd; skipping NPM_PUBLISH_ALL script.');
    return;
  }

  let bare = '';
  try {
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
    const nm = typeof pkg.name === 'string' ? pkg.name : '';
    bare = nm.startsWith('@') ? nm.split('/').slice(1).join('/') : nm;
  } catch {
    /* ignore */
  }
  if (!bare) {
    core.warning(
      'NPM_PUBLISH_ALL: package.json has no usable "name"; script not generated.'
    );
    return;
  }

  const scriptDir = process.env['RUNNER_TEMP'] || process.cwd();
  const scriptPath = path.join(scriptDir, 'setup-node-publish-all.sh');

  const lines: string[] = [
    '#!/usr/bin/env bash',
    'set -e',
    '',
    '# Auto-generated by actions/setup-node (npm-registries).',
    '# Publishes ./package.json to every scoped entry in the npm-registries input.',
    '# Any args passed here are forwarded verbatim to each `npm publish`.',
    '',
    `BARE=${JSON.stringify(bare)}`,
    ''
  ];
  for (const s of scopes) {
    lines.push(`echo "==> Publishing ${s}/$BARE"`);
    lines.push(`npm pkg set name=${s}/"$BARE"`);
    lines.push('npm publish "$@"');
    lines.push('');
  }

  fs.writeFileSync(scriptPath, lines.join('\n'));
  fs.chmodSync(scriptPath, 0o755);
  core.exportVariable('NPM_PUBLISH_ALL', scriptPath);
  core.info(
    `NPM_PUBLISH_ALL script generated at ${scriptPath} for ${scopes.length} scope(s): ${scopes.join(', ')}`
  );
}

/**
 * Rewrites the `name` field of the given package.json so its scope matches
 * `publishScope`. This is what makes `npm publish` target the input scope's
 * registry instead of the scope hardcoded in package.json.
 *
 *   name: "@foo/my-lib" + publishScope "@bar"  -> "@bar/my-lib"
 *   name: "my-lib"      + publishScope "@bar"  -> "@bar/my-lib"
 */
function applyPublishScope(publishScope: string, packageJsonPath: string) {
  if (!publishScope) return;

  let scope = publishScope.trim();
  if (!scope.startsWith('@')) scope = '@' + scope;
  scope = scope.toLowerCase();

  const resolved = path.resolve(process.cwd(), packageJsonPath);
  if (!fs.existsSync(resolved)) {
    core.warning(
      `npm-registries has a scoped entry but package.json was not found at ${resolved}; skipping name rewrite.`
    );
    return;
  }

  const raw = fs.readFileSync(resolved, 'utf8');
  let pkg: {name?: string; [k: string]: unknown};
  try {
    pkg = JSON.parse(raw);
  } catch (e) {
    core.warning(`Could not parse ${resolved}: ${(e as Error).message}`);
    return;
  }

  const currentName = typeof pkg.name === 'string' ? pkg.name : '';
  const bare = currentName.startsWith('@')
    ? currentName.split('/').slice(1).join('/')
    : currentName;

  if (!bare) {
    core.warning(
      `Cannot apply publish scope: package.json has no usable "name" field.`
    );
    return;
  }

  const newName = `${scope}/${bare}`;
  if (newName === currentName) {
    core.info(`publish scope: package name already "${newName}", no rewrite.`);
    return;
  }

  pkg.name = newName;
  fs.writeFileSync(resolved, JSON.stringify(pkg, null, 2) + '\n');
  core.info(
    `publish scope: rewrote package name "${currentName}" -> "${newName}" in ${resolved}`
  );
}

function writeRegistryToFile(registryUrl: string, fileLocation: string) {
  let scope: string = core.getInput('scope');
  if (!scope && registryUrl.indexOf('npm.pkg.github.com') > -1) {
    scope = github.context.repo.owner;
  }
  if (scope && scope[0] != '@') {
    scope = '@' + scope;
  }
  if (scope) {
    scope = scope.toLowerCase() + ':';
  }

  core.debug(`Setting auth in ${fileLocation}`);
  let newContents = '';
  if (fs.existsSync(fileLocation)) {
    const curContents: string = fs.readFileSync(fileLocation, 'utf8');
    curContents.split(os.EOL).forEach((line: string) => {
      // Add current contents unless they are setting the registry
      if (!line.toLowerCase().startsWith(`${scope}registry`)) {
        newContents += line + os.EOL;
      }
    });
  }
  // Remove http: or https: from front of registry.
  const authString: string =
    registryUrl.replace(/(^\w+:|^)/, '') + ':_authToken=${NODE_AUTH_TOKEN}';
  const registryString = `${scope}registry=${registryUrl}`;
  newContents += `${authString}${os.EOL}${registryString}`;
  fs.writeFileSync(fileLocation, newContents);
  core.exportVariable('NPM_CONFIG_USERCONFIG', fileLocation);
  // Only export NODE_AUTH_TOKEN if explicitly provided by user
  if (Object.prototype.hasOwnProperty.call(process.env, 'NODE_AUTH_TOKEN')) {
    core.exportVariable('NODE_AUTH_TOKEN', process.env.NODE_AUTH_TOKEN);
  }
}
